DSERV-257 load EBI protein complex
IGVF-DACC/igvf-catalog pull request #110
Opened 2023-09-27 17:46 UTC by shengchd

- Adapter for loading EBI protein complex from tsv file
- Script for generating dict containing binding regions from complex API

2023-09-28 18:08 UTC, pedrohr commented on data/data_loading_support_files/EBI_complex/get_EBI_complex_linkedFeatures.py
> +    complex_json = response = requests.get(url).json()
the `complex_json =` can be removed

2023-09-28 18:09 UTC, pedrohr approved these changes

2023-10-10 23:55 UTC, shengchd commented
Removed complex-complex loading part for DSERV-287.

2023-10-11 18:08 UTC, pedrohr commented on data/dev_setup.py
> +    'complex_complex': EBIComplex('./samples/EBI_complex.tsv', label='complex_complex'),
this line can be removed too

2023-10-11 18:09 UTC, pedrohr requested changes
just one line to be removed in the dev_setup script

2023-10-11 18:22 UTC, pedrohr approved these changes

2023-10-11 18:41 UTC, merged