DSERV-368-mouse-variants
IGVF-DACC/igvf-catalog pull request #229
Opened 2024-04-22 19:21 UTC by mingjiecn

2024-04-22 19:53 UTC, pedrohr requested changes
all 💯 
just a suggestion to rename the adapter class

2024-04-22 20:00 UTC, shengchd reviewed
Looks good to me

2024-04-23 21:49 UTC, pedrohr approved these changes

2024-04-26 18:20 UTC, pedrohr approved these changes

2024-05-07 13:59 UTC, merged