DSERV-96-enhancer-gene-link
IGVF-DACC/igvf-catalog pull request #47
Opened 2023-05-12 19:30 UTC by mingjiecn

2023-05-12 20:12 UTC, hitz requested changes

2023-05-12 20:12 UTC, hitz commented on data/adapters/encode_enhancer_gene_adapter.py
> +                if self.label == 'element_gene_link':
I think we should remove _link both here and from the variant_gene_link.  I know I wrote it that way though.  I haven't written that ticket though so I guess leave it be for now.

2023-05-12 20:12 UTC, hitz commented on data/adapters/encode_enhancer_gene_adapter.py
> +                        'source': self.source,
this needs chr and start and stop too?

2023-05-12 20:12 UTC, hitz commented on data/schema-config.yaml
> +  accessible_via:
this whole stanza needs to be copied to the other schema

2023-05-12 20:13 UTC, hitz commented on data/schema-config.yaml
> +  accessible_via:
WRONG

2023-05-12 20:13 UTC, hitz approved these changes

2023-05-12 20:13 UTC, hitz commented on data/adapters/encode_enhancer_gene_adapter.py
> +                        'source': self.source,
never mind this is fine

2023-05-15 16:48 UTC, pedrohr approved these changes

2023-05-15 18:56 UTC, merged