DSERV-198 updating db collection names
IGVF-DACC/igvf-catalog pull request #70
Opened 2023-06-19 22:24 UTC by pedrohr

2023-06-20 17:03 UTC, mingjiecn commented on data/schema-config.yaml
> +  db_collection_name: variant_genes
should be variants_genes?

2023-06-20 17:03 UTC, mingjiecn requested changes
See my comment for requested changes. Thank you!

2023-06-20 17:03 UTC, mingjiecn commented on data/schema-config.yaml
> +  db_collection_name: variant_genes
should be variants_genes?

2023-06-20 17:50 UTC, pedrohr commented on data/schema-config.yaml
> +  db_collection_name: variant_genes
yes, good catch! just pushed the change

2023-06-20 18:13 UTC, mingjiecn approved these changes

2023-06-22 14:27 UTC, mingjiecn approved these changes

2023-06-22 18:13 UTC, merged