DSERV-214 Genes API
IGVF-DACC/igvf-catalog pull request #81
Opened 2023-07-19 01:01 UTC by pedrohr

2023-07-19 21:33 UTC, mingjiecn approved these changes

2023-07-19 21:51 UTC, mingjiecn requested changes
Forgot one thing, We also need to query gene by item in alias. I don't see it in code?

2023-07-20 01:36 UTC, mingjiecn approved these changes

2023-07-21 22:11 UTC, pedrohr commented on src/routers/datatypeRouters/nodes/genes.ts
> +async function conditionalSearch (input: paramsFormatType): Promise<any[]> {
I'm possibly refactoring this method into a helper in the future if I find a way to dynamically remove keys from objects in typescript

2023-07-24 18:35 UTC, merged