DSERV-133-pathway
IGVF-DACC/igvf-catalog pull request #84
Opened 2023-07-20 15:09 UTC by mingjiecn

2023-07-20 17:37 UTC, pedrohr commented on data/adapters/reactome_pathway_adapter.py
> +                        query = 'https://reactome.org/ContentService/data/query/' + id
I'm thinking of ways of avoiding this, so we don't depend on their API to be functional... a few options I thought of:

* do they offer any data download that we can keep somewhere?
* run this script once and save all responses in a file and keep that versioned

do you have any other ideas?

2023-07-20 19:02 UTC, pedrohr approved these changes
Dataset is small! All good for the API solution 👍

2023-07-21 17:47 UTC, hitz requested changes

2023-07-21 17:47 UTC, hitz commented on data/schema-config.yaml
> +    properties:
add type: parent

2023-07-21 17:47 UTC, hitz commented on data/schema-config.yaml
> +    properties:
add type: child

2023-07-21 19:46 UTC, hitz approved these changes

2023-07-22 14:28 UTC, merged